sudo: false
install: true
addons:
  sonarcloud:
    organization: "anniemo1002-github"
    token:
      secure: 0beea288bd05a9ab834c5198045943614e8c1741
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
