sudo: false
install: true
addons:
  sonarcloud:
    organization: anniemo1002-github
    token:
      secure: QNRxuj2eqGqjoChrCczc
jdk:
  - oraclejdk8
script:
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
