sudo: false
install: true
addons:
  sonarcloud:
    organization: anniemo1002-github
    token:
      secure: c983162b7a32ec63aca31cc43b652f40976ff3d3
jdk:
  - oraclejdk8
script:
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
